### ISSUE TITLE
Can this be considered as a special method of meta-learning?

### ISSUE THREAD

**Issue by IDKiro** [hejingwenhejingwen/AdaFM#5]
And have you tried using meta-learning to generate AdaFM instead of adjusting the weight of AdaFM?

**Comment by hejingwenhejingwen** [comment]
In fact, we use meta-learning to generate the weights of AdaFM at the very begining. However, we found that this approach brought imbalanced converging speed for the "start" and "end" levels. Specifically, the "end" level, which is with relatively severe degradation, could achieve convergence much faster. 
Therefore, we first train a basic model for the "start" level, and then adjust the AdaFM's weights for the "end" level, which has been demonstrated to be efficient. Moreover, since the basic model is fixed, we are free to learn any AdaFM for any "end" level.
